# Generated by Django 3.2.8 on 2021-12-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datahub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='rguser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('ufname', models.CharField(max_length=100)),
                ('ulname', models.CharField(max_length=100)),
                ('uemail', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=16)),
                ('photo', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='uscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
