# Generated by Django 3.2.8 on 2021-12-15 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sem5', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rguser',
            name='photo',
        ),
    ]
