# Generated by Django 3.2.8 on 2021-12-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem5', '0003_auto_20211221_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uscore',
            name='index',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
