# Generated by Django 3.2.8 on 2021-12-21 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sem5', '0004_alter_uscore_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uscore',
            name='username',
        ),
        migrations.AddField(
            model_name='uscore',
            name='username_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
